
-- 7. Daily Challenges Table
create table if not exists public.user_challenges (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    challenge_id text not null,
    pool int not null, -- 10 or 20
    progress int default 0,
    target int not null,
    is_completed boolean default false,
    assigned_at date default current_date,
    reward_claimed boolean default false
);

alter table public.user_challenges enable row level security;

create policy "Users can view own challenges."
  on public.user_challenges for select
  using ( auth.uid() = user_id );

create policy "Users can insert own challenges."
  on public.user_challenges for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own challenges."
  on public.user_challenges for update
  using ( auth.uid() = user_id );
