-- 1. Profiles Table (Coins & Daily Login)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  nickname text,
  coins bigint default 0,
  last_daily_claim text -- Stored as ISO date string 'YYYY-MM-DD'
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- 2. Claimed Badges Table
create table if not exists public.claimed_badges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  badge_id text not null,
  claimed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, badge_id)
);

alter table public.claimed_badges enable row level security;

create policy "Users can view own claimed badges."
  on public.claimed_badges for select
  using ( auth.uid() = user_id );

create policy "Users can insert own claimed badges."
  on public.claimed_badges for insert
  with check ( auth.uid() = user_id );

-- 3. Bug Reports Table (just in case)
create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  nickname text,
  contact text,
  message text,
  page text,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.bug_reports enable row level security;

create policy "Anyone can insert bug reports."
  on public.bug_reports for insert
  with check ( true );

-- 4. Stats Table (Leaderboard etc)
create table if not exists public.stats (
    user_id uuid references auth.users on delete cascade not null primary key,
    nickname text,
    lists_played int default 0,
    games_played int default 0,
    wins int default 0,
    losses int default 0,
    grand_wins int default 0,
    null_wins int default 0,
    ramsch_wins int default 0,
    rollmops_wins int default 0,
    big_busch int default 0,
    trumpf_count int default 0,
    schneider_wins int default 0,
    schwarz_wins int default 0,
    hand_wins int default 0,
    grand_ouvert_wins int default 0,
    null_ouvert_wins int default 0,
    best_streak int default 0,
    won_all_in_list_count int default 0,
    win_grand_ohne_4_wins int default 0,
    
    -- New columns for badges
    null_no7_wins int default 0,
    eichel_wins int default 0,
    gruen_wins int default 0,
    rot_wins int default 0,
    schellen_wins int default 0,
    ramsch_zero_wins int default 0,

    updated_at timestamp with time zone
);

alter table public.stats enable row level security;

create policy "Stats are viewable by everyone."
  on public.stats for select
  using ( true );

create policy "Users can insert their own stats."
  on public.stats for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own stats."
  on public.stats for update
  using ( auth.uid() = user_id );

-- 5. History Table
create table if not exists public.history (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    date text,
    rounds int,
    rule_set text,
    score_bot2 int,
    score_bot1 int,
    score_player int,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.history enable row level security;

create policy "Users can view own history."
  on public.history for select
  using ( auth.uid() = user_id );

create policy "Users can insert own history."
  on public.history for insert
  with check ( auth.uid() = user_id );

-- 6. Badges Table (Tracks unlocked badges, separate from claimed rewards)
create table if not exists public.badges (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    badge_id text not null,
    unlocked_at timestamp with time zone default timezone('utc'::text, now()),
    unique(user_id, badge_id)
);

alter table public.badges enable row level security;

create policy "Users can view own badges."
  on public.badges for select
  using ( auth.uid() = user_id );

create policy "Users can insert own badges."
  on public.badges for insert
  with check ( auth.uid() = user_id );
