-- Fix for Daily Challenges Table
-- This ensures the user_challenges table exists with all required columns

-- 1. Create table if it doesn't exist
create table if not exists public.user_challenges (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    challenge_id text not null,
    pool int not null,
    progress int default 0,
    target int not null,
    is_completed boolean default false,
    assigned_at date default current_date,
    reward_claimed boolean default false
);

-- 2. Add missing columns if they don't exist
ALTER TABLE public.user_challenges ADD COLUMN IF NOT EXISTS reward_claimed boolean default false;

-- 3. Enable RLS
ALTER TABLE public.user_challenges ENABLE ROW LEVEL SECURITY;

-- 4. Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Users can view own challenges." ON public.user_challenges;
DROP POLICY IF EXISTS "Users can insert own challenges." ON public.user_challenges;
DROP POLICY IF EXISTS "Users can update own challenges." ON public.user_challenges;

-- 5. Create policies
CREATE POLICY "Users can view own challenges."
  ON public.user_challenges FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own challenges."
  ON public.user_challenges FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own challenges."
  ON public.user_challenges FOR UPDATE
  USING (auth.uid() = user_id);

-- 6. Reload Supabase schema cache
NOTIFY pgrst, 'reload schema';
